name: HTTP Notification System

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
      - run: redis-cli ping
      - name: Copy .env
        run: php -r "copy('.env.testing', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist  --ignore-platform-reqs
      - name: Generate key and optimize
        run: php artisan key:generate
      - name: Run redis queue
        run: php artisan queue:work
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit -d memory_limit=-1 tests/Feature

